version: "2"
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./generate_prod_swagger.json:/usr/share/nginx/html/sample.yaml
    environment:
      API_URL: sample.yaml
    ports:
      - "1000:8080"
