swagger: "2.0"
info:
  vesion: "1.0.0"
  description: "クーポン情報を返却するAPIです"
  title: "CouponsApi"
tags:
  - name: coupons
    description: "クーポン情報を返却するAPI群"
schemes:
  - "https"
paths:
  /coupons:
    get:
      tags:
        - coupons
      summary: "一覧取得API(期間指定可)"
      description: "全てのクーポン情報を返却します。期間を指定した場合、その間利用可能なクーポン一覧を返却します。"
      parameters:
      - name: "startdate"
        in: "query"
        description: "利用開始日付"
        required: false
        type: "integer"
      - name: "enddate"
        in: "query"
        description: "利用終了日付"
        required: false
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/apiResponse"
        400:
          description: "Invalid input."
        500:
          description: "Internal server error."
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetListFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    post:
      tags:
        - coupons
      summary: "一覧取得API(期間指定可)"
      description: "全てのクーポン情報を返却します。期間を指定した場合、その間利用可能なクーポン一覧を返却します。"
      parameters:
      - name: "PostBody"
        in: "body"
        description: "利用開始日付(startdate)と利用終了日付(enddate)をキーとしたJSONをHTTPリクエストのボディ部に設定してください。"
        required: true
        schema:
          $ref: "#/definitions/usagePeriod"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/apiResponse"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetListFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    options:
      tags:
        - coupons
      summary: "CORS Support API"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /coupons/{id}:
    get:
      tags:
        - coupons
      summary: "id指定取得API"
      description: "指定されたidのクーポン情報を返します"
      parameters:
      - name: "id"
        in: "path"
        description: "クーポン毎に割り当てられている一意なidを指定してください"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/apiResponse"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetIdFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
definitions:
  coupon:
    type: "object"
    properties:
      id:
        type: "string"
      coupon-image:
        type: "string"
      qr-image:
        type: "string"
      explain:
        type: "string"
      start-date:
        type: "string"
      end-date:
        type: "string"
  apiResponse:
    type: "object"
    required:
    - "response"
    properties:
      header:
        type: "object"
        properties:
          status:
            type: "string"
          errors:
            type: "array"
            items:
              properties:
                filed:
                  type: "string"
                message:
                  type: "string"
      response:
        type: "object"
        properties:
          coupons:
            type: "array"
            items:
              $ref: '#/definitions/coupon'
  usagePeriod:
    type: "object"
    required:
    - "startdate"
    - "enddate"
    properties:
      startdate:
        type: "string"
      enddate:
        type: "string"
