swagger: "2.0"
info:
  vesion: "1.0.0"
  description: "This is CouponsAPI"
  title: "Coupons Api"
schemes:
  - "https"
paths:
  /coupons:
    get:
      summary: "クーポン一覧API"
      description: "クーポンの全て情報を返します。期間を指定した場合、その間利用可能なクーポン一覧を返却します。"
      parameters:
      - name: "startdate"
        in: "query"
        description: "利用開始日付"
        required: false
        type: "integer"
      - name: "enddate"
        in: "query"
        description: "利用終了日付"
        required: false
        type: "integer"
      responses:
        200:
          description: "Matches Objects."
          schema:
            $ref: "#definitions/coupons"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetListFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    post:
      summary: "クーポン一覧API"
      description: "クーポンの全て情報を返します。期間を指定した場合、その間利用可能なクーポン一覧を返却します。"
      parameters:
      - name: "PostBody"
        in: "body"
        description: "利用開始日付"
        required: true
        schema:
          $ref: "#/definitions/usagePeriod"
      responses:
        200:
          description: "Matches Objects."
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetListFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'POST,GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        type: "mock"
  /coupons/{id}:
    get:
      summary: "クーポン情報API"
      description: "指定されたidのクーポンの情報を返します"
      parameters:
      - name: "id"
        in: "path"
        description: "クーポンのID"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${couponsGetIdFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
definitions:
  coupons:
    type: "object"
    required:
    - "response"
    properties:
      header:
        type: "object"
        status:
          type: "string"
        errors:
          type: "array"
      response:
        type: "object"
  usagePeriod:
    type: "object"
    required:
    - "enddate"
    - "startdate"
    properties:
      enddate:
        type: "string"
      startdate:
        type: "string"
