version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
      PIPENV_VENV_IN_PROJECT: "true"
      AWS_DEFAULT_REGION: "ap-northeast-1"
      AWS_SAM_LOCAL: "true"
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - run:
          name: "Install pip modules for test"
          command: |
            pip install pipenv
            pip install aws-sam-cli
      - run:
          name: "Create LocaStack"
          command: |
            docker-compose up -d
            ./script/createDynamo.sh localstack
      - run:
          name: "Install dependencies"
          command: |
            cd lambdaFunctions/
            make dep-dev
      - run:
          name: "Run tests"
          command: |
            cd lambdaFunctions/
            make test
      - run:
          name: "Send codecov"
          command: |
            cd lambdaFunctions/
            pipenv run codecov
